services:
  dashboard:
    build: .
    image: bioscape-phenology-explorer:latest
    ports:
      - "80:8050"
    environment:
      VI_DATACUBE_ROOT: /data
    volumes:
      - /media/volume/Bioscape_Dashboard_Data/phenology_data:/data:ro
    restart: unless-stopped
    mem_limit: 5g
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
